# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180318_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_type', models.CharField(max_length=50)),
                ('D_name', models.CharField(max_length=50)),
                ('D_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(max_length=50)),
                ('S_id', models.CharField(max_length=50)),
                ('S_area', models.CharField(max_length=50)),
                ('S_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
