# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_device_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2232, max_length=50),
            preserve_default=False,
        ),
    ]
