# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-24 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180324_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_phone',
            new_name='phone',
        ),
    ]
