# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180324_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
