# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
